### ISSUE TITLE
DI Component and paginator

### ISSUE THREAD

**Issue by Krafcu** [rochamarcelo/cake-pimple-di#1]
Hi,
big thanks for the plugin. It realy helped me out solving some DI problems i had before. 
I like the elegance using DI Component in Controllers however i have a problem in generating urls with  paginator.

For example looking at this code:

``` php
class ExampleController extends AppController
{
    public function initialize()
    {
        parent::initialize();
        $this->loadComponent('RochaMarcelo/CakePimpleDi.Di', [
            'injections' => [
                'index' => [//View action
                    'Http\Client'
                ]
            ]
        ]);
        $this->loadComponent('Paginator');
    }

    public function index(Client $client)
    {
        $response = $client->get('some_api_url');

        $data = $this->paginate($this->Examples->find());

        $this->set('data', $data);
        $this->set('api_data', $response);
    }
}
```

then in `index.ctp` for example this:

``` php
<th><?= $this->Paginator->sort('id', __('ID')) ?></th>
```

gives me this warning:
`rawurlencode() expects parameter 1 to be string, object given [CORE/src/Routing/Route/Route.php, line 568]` as it tries to lookup the parameter for creating the url.
I can solve the issue simply by using DI trait directly in Controller or overwrite the url in view like this:

``` php
$this->Paginator->options(['url' => []]);
```

However I couldn't come up with some more elegant solution. Maybe you could point me out to some better directions, or find a way to solve the problem in the plugin component itself.

Best regards.

**Comment by rochamarcelo** [comment]
Hi,

Thanks to report it. I've been a lot busy lately but I'll take some time to look in to it this week.

Maybe a new Trait would work better than the component.

**Comment by rochamarcelo** [comment]
Fixed, thanks @Krafcu
