### ISSUE TITLE
di() should return \RochaMarcelo\CakePimpleDi\Di\Di in DiTrait

### ISSUE THREAD

**Issue by btaens** [rochamarcelo/cake-pimple-di#2]
Hello, great plugin.

One small problem is with the type hinting.
`DiTrait`'s `di()` function is typehinted as `@return RochaMarcelo\CakePimpleDi\Di\Di`.
The IDE can't recognize it this way. It should be `@return \RochaMarcelo\CakePimpleDi\Di\Di`.

Have you thought about submitting the plugin to https://github.com/FriendsOfCake/awesome-cakephp ? It would give it a lot more visibility.

**Comment by rochamarcelo** [comment]
Hi, thanks for your report, it's okay now.

**Comment by rochamarcelo** [comment]
I'll submit the plugin to  https://github.com/FriendsOfCake/awesome-cakephp as soon as possible.
