### ISSUE TITLE
Request And Session Objects Optionally Added To Container

### ISSUE THREAD

**Issue by T0mats0** [rochamarcelo/cake-pimple-di#3]
I would like to propose the Session and Request objects be added to the container through a beforeDispatch listener. This would be an optional event listener users could add to their bootstrap or in 3.6 Plugin class. 

Something like this in the bootstrap

```php
$manager = \Cake\Event\EventManager::instance();
$manager->on('Dispatcher.beforeDispatch', new ContainerDispatchListener);
```
The invokable would then have a method like this:

```php
       public function __invoke(Event $event, ServerRequest $request)
        {
            $container = Di::instance()->container();
            $container['request'] = $request;
            $container['session'] = $request->getSession();
        }
```

Let me know what you think, happy to do a pull request.

**Comment by rochamarcelo** [comment]
Hi,

sounds good. What is your use case?

Thanks.

**Comment by T0mats0** [comment]
I have a user session object that requires the session to construct. That user session object has a trait that is shared by a helper and a component. I want the user session object in the container so I can get the same object out each time  I pull it out for the helper or the component. I also use it with a date time helper I have to set the timezone for the user. It's a very handy thing to have to make it easy to test for different roles, permissions, timezones, logged in status, activity etc.

**Comment by rochamarcelo** [comment]
It is good to have as an option. 

Just keep in mind that with newer versions of cakephp, request object is immutable.

Please send a pull request.

**Comment by rochamarcelo** [comment]
Thank you.
