### ISSUE TITLE
CakePHP 4 Support

### ISSUE THREAD

**Issue by josephshanak** [rochamarcelo/cake-pimple-di#7]
I am currently using this plugin in a CakePHP3 application that is preparing to upgrade to CakePHP 4, and I would like to know what your plans are for maintaining this plugin now that CakePHP 4 is out. Are there plans on updating this plugin to support CakePHP 4?

**Comment by rochamarcelo** [comment]
Hi, yes I'm planning to upgrade soon

**Comment by josephshanak** [comment]
> Hi, yes I'm planning to upgrade soon

@rochamarcelo, thank you for the response, and I'm glad to hear you will be upgrading. Do you have an idea of the timeline?
